baseURL = "https://teshi.org/"
title = "Teshi"
languageCode = "en"
enableRobotsTXT = true
enableEmoji = false
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "404"]

[outputs]
  home = ["HTML"]

[params]
  description = "Teshi — AI Testing Agent"

[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
